### ISSUE TITLE
SubFolder is not created but a file  with subfolders directory name is created

### ISSUE THREAD

**Issue by RAIESHG** [SushanShakya/flutter_folder_structure_generator#4]
![image](https://user-images.githubusercontent.com/48977936/165682998-27ce7c6b-a09a-4a1e-80eb-1714f2a0360c.png)

**Comment by SushanShakya** [comment]
Are you on Linux ?

**Comment by SushanShakya** [comment]
or Mac OS ?

**Comment by SushanShakya** [comment]
Currently the extension only works for Windows system.. Need to update to support Unix based systems

**Comment by RAIESHG** [comment]
I am on linux

**Comment by SushanShakya** [comment]
You'll have to change the way folder are generated in the extension ! 
For windows the file path is given as "E:\\home\\" in linux its "E:/home/"

**Comment by RAIESHG** [comment]
Gotcha! Thankyou
