### ISSUE TITLE
Not working well on Mac

### ISSUE THREAD

**Issue by jabguru** [SushanShakya/flutter_folder_structure_generator#5]
I installed the extension, but it doesn't work well because "\" is used instead of "/"

**Comment by SushanShakya** [comment]
Hey.. 
If you're running anything other than Windows... 
The extension will not work.

**Comment by SushanShakya** [comment]
I still have not initiated support for Unix based machines

**Comment by jabguru** [comment]
Oh Wow, i tried it, the only issue I see is the backslash and forward slash

It's a very nice extension, is there hope on the support anytime soon?
Not used to vs code extension I would have done it and made a pull request.
But I'll still look into it and see if it's something I can fix.

**Comment by SushanShakya** [comment]
I believe  we only have to do the OS check and change "\\" with "/" for Unix based OS.
I haven't had the time lately to do it so it's stuck.

**Comment by SushanShakya** [comment]
Plus I don't owe a Unix based machine to test it on.
Which is also a factor.

**Comment by SushanShakya** [comment]
Hey.. I just updated the extension to support Unix based system
Please update your extension, try again, and let me know if it works.

**Comment by jabguru** [comment]
It's working now. Thanks a lot for your effort!
